export const Users = [
  {
    id: 11,
    username: "FrankStallone",
    email: "frank@stallone.com",
    password: "123123123123",
    profileImage: "person/viking.jpg",
    coverImage: "post/1.jpg",
    desc: "I'm a viking - I plunder",
    city: "Valhalla",
    from: "Asgard",
    dream: "To hold Mjolnir",
    friends: [],
    minions: [],
    isAdmin: false,
  },
  {
    id: 2,
    username: "Shirley Templeton",
    email: "shirley@templeton.com",
    profileImage: "person/2.jpg",
    coverImage: "post/3.jpg",
    desc: "Single mom of 4",
    city: "Detroit",
    from: "Topeka",
    dream: "To be a good mom",
    friends: [],
    minions: [],
    isAdmin: false,
  },
  {
    id: 3,
    username: "Kathy Yates",
    email: "kathy@yates.com",
    profileImage: "person/3.jpg",
    coverImage: "post/3.jpg",
    desc: "Where's the beef?",
    city: "Atlanta",
    from: "Akron",
    dream: "To drive a semi",
    friends: [],
    minions: [],
    isAdmin: false,
  },
  {
    id: 4,
    username: "Deborah Gibson",
    email: "debbie@gibson.com",
    profileImage: "person/4.jpg",
    coverImage: "post/4.jpg",
    desc: "Have you ever seen the rain?",
    city: "Seattle",
    from: "San Diego",
    dream: "I want to be a pop star",
    friends: [],
    minions: [],
    isAdmin: false,
  },
  {
    id: 5,
    username: "MarkyMark",
    email: "mark@youcantescapeit.com",
    profileImage: "person/5.jpg",
    coverImage: "post/5.jpg",
    desc: "I'm a funky bunch",
    city: "Hollywood",
    from: "Boston",
    dream: "To be in New Kids with Donnie",
    friends: [],
    minions: [],
    isAdmin: false,
  },
  {
    id: 6,
    username: "Alabaster Jones",
    email: "frank@stallone.com",
    profileImage: "person/6.jpg",
    coverImage: "post/6.jpg",
  },
  {
    id: 7,
    username: "Freddie Mercury",
    profileImage: "person/7.jpg",
    coverImage: "post/7.jpg",
  },
  {
    id: 8,
    username: "Buster Douglas",
    profileImage: "person/8.jpg",
    coverImage: "post/8.jpg",
  },
  {
    id: 9,
    username: "Catherine Zeta-Jones",
    profileImage: "person/9.jpg",
    coverImage: "post/9.jpg",
  },
  {
    id: 10,
    username: "Olivia Newton-John",
    profileImage: "person/10.jpg",
    coverImage: "post/10.jpg",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Goonies never say die.",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Did you eat a lot of paint chips as a kid?",
    photo: "post/2.jpeg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 3,
    desc: "Forest for the trees, bruv.",
    photo: "post/3.jpeg",
    date: "5 mins ago",
    userId: 2,
    like: 32,
    comment: 9,
  },
  {
    id: 4,
    desc: "This is insane.",
    photo: "post/4.jpeg",
    date: "5 mins ago",
    userId: 9,
    like: 32,
    comment: 9,
  },
  {
    id: 5,
    desc: "Did you really just say that?",
    photo: "post/5.jpeg",
    date: "5 mins ago",
    userId: 10,
    like: 32,
    comment: 9,
  },
  {
    id: 6,
    desc: "One for all and all for money.",
    photo: "post/6.jpeg",
    date: "5 mins ago",
    userId: 7,
    like: 32,
    comment: 9,
  },
  {
    id: 7,
    photo: "post/7.jpeg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 8,
    desc: "Cocaine is a hell of a drug.",
    photo: "post/8.jpeg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 9,
    desc: "An apple a day costs about $30 a month.",
    photo: "post/9.jpeg",
    date: "5 mins ago",
    userId: 6,
    like: 32,
    comment: 9,
  },
  {
    id: 10,
    desc: "My doctor said something about greens.",
    photo: "post/10.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
];
